kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
node:
  machine: digitalocean
workspace:
  base: /go
  path: src/github.com/unknowntpo/todos
steps:
  - name: test
    image: golang:1.20.3
    commands:
      - make test