package page

import (
	"context"

	"github.com/unknowntpo/page/domain"

	connect "github.com/bufbuild/connect-go"
	// generated by protoc-gen-go
	// generated by protoc-gen-connect-go

	pb "github.com/unknowntpo/page/gen/proto/page"
)

func NewPageServer(uCase domain.PageUsecase) *pageServer {
	return &pageServer{useCase: uCase}
}

type pageServer struct {
	useCase domain.PageUsecase
}

// GetHead(context.Context, *connect_go.Request[page.GetHeadRequest]) (*connect_go.Response[page.GetHeadResponse], error)
// GetPage(context.Context, *connect_go.BidiStream[page.GetPageRequest, page.GetPageResponse]) error
// SetPage(context.Context, *connect_go.BidiStream[page.Page, page.SetPageResponse]) error

// GetHead(context.Context, *connect_go.Request[page.GetHeadRequest], *connect_go.ServerStream[page.PageKey]) error
// GetPage(context.Context, *connect_go.BidiStream[page.PageKey, page.Page]) error
// SetPage(context.Context, *connect_go.ClientStream[page.Page]) (*connect_go.Response[page.PageKey], error)

// type PageServiceHandler interface {
// 	GetHead(context.Context, *connect_go.Request[page.GetHeadRequest]) (*connect_go.Response[page.GetHeadResponse], error)
// 	GetPage(context.Context, *connect_go.BidiStream[page.GetPageRequest, page.GetPageResponse]) error
// 	SetPage(context.Context, *connect_go.BidiStream[page.Page, page.SetPageResponse]) error
// }

func (s *pageServer) GetHead(ctx context.Context, req *connect.Request[pb.GetHeadRequest]) (*connect.Response[pb.GetHeadResponse], error) {
	// log.Println("Request headers: ", req.Header())
	// res := connect.NewResponse(&pb.GreetResponse{
	// 	Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	// })
	// res.Header().Set("Greet-Version", "v1")
	// return res, nil
	return nil, nil
}

func (s *pageServer) GetPage(ctx context.Context, stream *connect.BidiStream[pb.GetPageRequest, pb.SetPageResponse]) error {
	// 	GetPage(context.Context, *connect_go.BidiStream[page.PageKey, page.Page]) error

	return nil
}

func (s *pageServer) SetPage(ctx context.Context, stream *connect.BidiStream[pb.GetPageRequest, pb.SetPageResponse]) error {
	// log.Println("Request headers: ", req.Header())
	// res := connect.NewResponse(&pb.ServerOption{
	// 	Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	// })
	// res.Header().Set("Greet-Version", "v1")
	// return res, nil
	// return nil, nil

	return nil
}

// func (s *pageServer) GetHead(req *pb.GetHeadRequest, stream pb.PageService_GetHeadServer) error {
// 	// TODO: Implement the logic to get the head page key
// 	// For example:
// 	var listKey domain.ListKey
// 	pageKey, err := s.useCase.GetHead(context.Background(), listKey)
// 	if err != nil {
// 		return errors.Wrap(err, "failed on api.useCase.GetHead")
// 	}

// 	// Send the page key through the stream
// 	if err := stream.Send(&pb.PageKey{Key: string(pageKey)}); err != nil {
// 		return err
// 	}

// 	return nil
// }

// func (s *pageServer) GetPage(stream pb.PageService_GetPageServer) error {
// 	// Receive the page keys from the stream and send the corresponding pages
// 	for {
// 		pageKey, err := stream.Recv()
// 		if err == io.EOF {
// 			return nil
// 		}
// 		if err != nil {
// 			return err
// 		}

// 		log.Println("got pageKey: ", pageKey)

// 		// TODO: Implement the logic to get the page
// 		// For example:
// 		page := &pb.Page{
// 			Title:   "Page Title",
// 			Content: "Page Content",
// 		}

// 		// Send the page through the stream
// 		if err := stream.Send(page); err != nil {
// 			return err
// 		}
// 	}
// }

// func (s *pageServer) SetPage(stream pb.PageService_SetPageServer) error {
// 	// Receive the pages from the stream and set them
// 	for {
// 		pg, err := stream.Recv()
// 		if err == io.EOF {
// 			return nil
// 		}
// 		if err != nil {
// 			return err
// 		}

// 		// TODO: Implement the logic to set the page
// 		// For example:
// 		pageKey := "ABC"
// 		log.Printf("Setting page %s: %s", pageKey, pg.Content)

// 		// Send the page key through the stream
// 		if err := stream.SendAndClose(&pb.PageKey{Key: pageKey}); err != nil {
// 			return err
// 		}
// 	}
// }
