name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ '1.19' ]
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --name my-redis-container
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Download dependencies
      run: go get ./...

    - name: Test
      run: make test